#!/usr/bin/env bash
set -euo pipefail

declare root_dir="$(git rev-parse --show-toplevel)"
declare hook_dir="$root_dir/.git/hooks"
declare pgm_dir="$(realpath --relative-to="$hook_dir" "$(dirname "${BASH_SOURCE[0]}")")"

for i in pre-commit; do
  ln -s "$pgm_dir/$i" "$hook_dir"
done