#!/usr/bin/env bash
set -euo pipefail

# todo: use the Gulp lint task. This requires adding support to Gulp
#       for specific files.

# $@ glob
git-staged-files() {
  git diff --cached -C -C -z --name-only --relative --diff-filter=ACMRTUXB -- "$@"
}

# $@ name
map() { IFS= read -rd $'\0' "$@"; }

git-staged-files \*.js|
while map file; do
  git show ":$file"|
  eslint --max-warnings 0 --stdin --stdin-filename "$file"
done

git-staged-files \*.json|
while map file; do
  git show ":$file"|
  jsonlint -q
done